config/routes.rb
Rails.application.routes.draw do

  resources :networks

  resources :users
  resources :homes

  root 'homes#index'
  
  
  get '/analytics' => 'networks#analytics'
  
  post '/deletetrackgoal' => 'networks#deletetrackgoal'
  post '/edittrackgoal' => 'networks#edittrackgoal'
  post '/addtrackgoal' => 'networks#addtrackgoal'

  get '/releasenotes' => 'networks#releasenotes'

  post '/campaignsettingupdate' => 'networks#campaignsettingupdate'

  post '/quickedit/keyword' => 'networks#quickeditkeyword'
  post '/quickadd/keyword' => 'networks#quickaddkeyword'

  get '/watchdog/history' => 'networks#watchdoghistory'

  post '/getwatchdogreport' => 'networks#getwatchdogreport'

  get '/pricing' => 'homes#pricing'
  get '/demo' => 'homes#demo'
  get '/contact_us' => 'homes#contact_us'
  get '/services' => 'homes#services'

  get '/services/search_engine_marketing' => 'homes#searchenginemarketing'
  get '/services/search_engine_optimization' => 'homes#searchengineoptimization'
  get '/services/social_media_marketing' => 'homes#socialmediamarketing'
  get '/services/content_localisation' => 'homes#contentlocalisation'

  post '/send_demo_email' => 'homes#send_demo_email'
  post '/send_contact_us_email' => 'homes#send_contact_us_email'

  get '/terms' => 'homes#terms'

  get '/demo_thank_you' => 'homes#demo_thank_you'
  get '/contact_us_thank_you' => 'homes#contact_us_thank_you'

  get '/cleanexportfile' => 'application#cleanexportfile'
  get '/cleanlogfile' => 'application#cleanlogfile'

  post '/getuser' => 'users#getuser'
  post '/edituser' => 'users#edituser'
  post '/switchuserstatus' => 'users#switchuserstatus'
  post '/createnewuser' => 'users#createnewuser'
  post '/removeuser' => 'users#removeuser'

  post '/campaign_api_sync' => 'networks#campaign_api_sync'
  post '/adgroup_api_sync' => 'networks#adgroup_api_sync'

  post '/createnetwork' => 'networks#createnetwork'
  post '/removenetwork' => 'networks#removenetwork'
  post '/getnetwork' => 'networks#getnetwork'
  post '/editnetwork' => 'networks#editnetwork'

  post '/csv' => 'networks#csv'
  get '/csv' => 'networks#csv'

  post '/login' => 'users#login'
  post '/logout' => 'users#logout'
  get '/logout' => 'users#logout'

  post '/updatepw' => 'users#updatepw'
  post '/updatemail' => 'users#updatemail'

  post '/addnetworkuser' => 'networks#addnetworkuser'
  post '/removenetworkuser' => 'networks#removenetworkuser'

  get '/dashboard' => 'homes#dashboard'
  get '/dashboard/detail' => 'homes#dashboarddetail'

  post '/getdashboard' => 'homes#getdashboard'

  post '/getdashboarddetail' => 'homes#getdashboarddetail'

  get '/account/' => 'users#account'
  get '/account/password' => 'users#editpassword'
  get '/account/user' => 'users#user'
  get '/account/tracking' => 'users#tracking'
  get '/account/portfolio' => 'users#portfolio'
  get '/account/goals' => 'users#goals' # leon goals

  get '/channel/accounts' => 'networks#channelaccounts'
  post '/getnetworkaccounts' => 'networks#getnetworkaccounts'
  post '/channel/sync' => 'networks#sync'

  get '/channel/:id/campaigns' => 'networks#campaigns'
  get '/campaigns' => 'networks#campaigns'
  get '/campaigns/:campaign_type' => 'networks#campaigns'
  get '/campaigns/:id/:type/:networkid/overview' => 'networks#campaignoverview'
  get '/campaigns/:id/:type/:networkid/setting' => 'networks#campaignsetting'
  get '/campaigns/:id/:type/:networkid/adgroup' => 'networks#campaignadgroup'

  get '/campaigns/:id/:type/:networkid/ads' => 'networks#campaignads'
  get '/campaigns/:id/:type/:networkid/adgroup/:adgroupid/ads' => 'networks#campaignads'

  get '/campaigns/:id/:type/:networkid/keyword' => 'networks#campaignkeyword'
  get '/campaigns/:id/:type/:networkid/adgroup/:adgroupid/keyword' => 'networks#campaignkeyword'

  get '/clickactivity/:type/:id' => 'networks#clickactivity'

  post '/getclickactivity' => 'networks#getclickactivity'

  post '/getcampaigns' => 'networks#getcampaigns'

  post '/getcampaignoverview' => 'networks#getcampaignoverview'

  post '/getcampaignadgroup' => 'networks#getcampaignadgroup'

  post '/getcampaignads' => 'networks#getcampaignads'

  post '/getcampaignkeyword' => 'networks#getcampaignkeyword'

  get '/getevent' => 'application#getevent'

  get '/get_event' => 'application#event'
  get '/event' => 'application#event'

  get '/getclick' => 'application#getclick'
  get '/click' => 'application#click'

  post '/sogous/updatead' => 'networks#sogouupdatead'
  post '/threesixties/updatead' => 'networks#threesixtyupdatead'
  post '/baidu/updatead' => 'networks#baiduupdatead'
  post '/shenmas/updatead' => 'networks#shenmaupdatead'

  post '/sogous/updatekeyword' => 'networks#sogouupdatekeyword'
  post '/threesixties/updatekeyword' => 'networks#threesixtyupdatekeyword'
  post '/baidu/updatekeyword' => 'networks#baiduupdatekeyword'
  post '/shenmas/updatekeyword' => 'networks#shenmaupdatekeyword'

  post '/sogous/updateadgroup' => 'networks#sogouupdateadgroup'
  post '/threesixties/updateadgroup' => 'networks#threesixtyupdateadgroup'
  post '/baidu/updateadgroup' => 'networks#baiduupdateadgroup'
  post '/shenmas/updateadgroup' => 'networks#shenmaupdateadgroup'

  post '/updatecampaign' => 'networks#allupdatecampaign'

  get '/advancedsearch' => 'networks#advancedsearch'
  get '/advancedsearchistory' => 'networks#advancedsearchistory'

  get '/getallleveldata' => 'networks#getallleveldata'
  post '/getallleveldata' => 'networks#getallleveldata'

  get '/getconversion' => 'application#getconversion'

  get '/bulkupload/add' => 'networks#bulkuploadadd'
  get '/bulkupload/edit' => 'networks#bulkuploadedit'
  get '/bulk/summary' => 'networks#bulksummary'

  post '/getbulkjob' => 'networks#getbulkjob'
  post '/cancelbulkjob' => 'networks#cancelbulkjob'
  post '/resumebulkjob' => 'networks#resumebulkjob'

  post '/bulkaddcampaign' => 'networks#bulkaddcampaign'
  post '/bulkaddadgroup' => 'networks#bulkaddadgroup'
  post '/bulkaddad' => 'networks#bulkaddad'
  post '/bulkaddkeyword' => 'networks#bulkaddkeyword'

  post '/bulkeditcampaign' => 'networks#bulkeditcampaign'

  post '/advancesearchjob' => 'networks#advancesearchjob'
  post '/advancesearchjobupdate' => 'networks#advancesearchjobupdate'
  post '/canceladvancesearchjob' => 'networks#canceladvancesearchjob'

  post '/advancesearchadgroup' => 'networks#advancesearchadgroup'
  post '/advancesearchadgroupupdate' => 'networks#advancesearchadgroupupdate'

  post '/getadvancesearch' => 'networks#getadvancesearch'

  post '/getcampaignbynetworkid/:id' => 'networks#getcampaignbynetworkid'

  post '/getadgroupbycampaignid/:type/:id' => 'networks#getadgroupbycampaignid'

  get '/test' => 'application#test'

  get '*unmatched_route' => 'application#not_found'

end

app/models/network.rb
class Network < ActiveRecord::Base
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/views/networks/bulkuploadadd.html.erb
<div class="content_title">Bulk Upload</div>
<ul class="tab_menu">
	<li><a class="tab_tag history_log_tag active" href="javascript:;">Add</a></li>
	<li><a class="tab_tag history_log_tag" href="/bulkupload/edit">Edit</a></li>
	<li><a class="tab_tag search_tag" href="/bulk/summary">Summary</a></li>
</ul>

<%
port_array = [81,83,89]
# port_array = [81]
random_port = port_array.shuffle.sample
%>

<div class="content_outer">
	<div class="content_core">
		
		<div class="content_core_title">Use spreadsheets to make bulk changes to your campaigns</div>
		<hr>
		
		<div class="content_form">
			
			<div class="content_form">
				<form action="http://china.adeqo.com:<%=random_port.to_s%>/bulkjob" method="post" id="uploadForm" enctype="multipart/form-data" autocomplete="off" target="hiddenUploadIframe">
					
					<div class="form_row">
						<div class="content_form_label">
							<label class="form_label">Upload type:</label>
							<div class="clearfix"></div>
						</div>
						
						<div class="content_form_input">
							<input type="radio" name="upload_type" value="campaigns" checked> <label>Campaigns</label>
							<input type="radio" name="upload_type" value="adgroup"> <label>Ad Groups</label>
							<input type="radio" name="upload_type" value="ad"> <label>Ads</label>
							<input type="radio" name="upload_type" value="keyword"> <label>Keywords</label>
						</div>
						<div class="clearfix"></div>
					</div>
					<hr>
					
					<div class="form_row">
						<div class="content_form_label" style="min-width:400px;">
							<label class="form_label">Please select channel and account:</label>
							<div class="clearfix"></div>
						</div>
						
						<div class="content_form_input">
							<select class="form_field" name="account" id="account">
								<%
								usernetwork_array = []
								@user_network = @db[:network_user].find('user' => session[:user_id].to_i)
								@db.close
								
								@user_network.each do |usernetwork|
									usernetwork_array << usernetwork["network_id"].to_i
								end
								
								# @networks = @db[:network].find('company_id' => @user_company_id.to_i)
								@networks = @db[:network].find('id' => { "$in" => usernetwork_array})
								@db.close()
								if @networks.count.to_i > 0
									@networks.each do |network|
										%><option name="<%=network['type']%>" value="<%=network['id']%>"><%=network['name']%></option><%
									end
								end
								%>
							</select>
						</div>
						<div class="clearfix"></div>
						
					</div>
					<hr>
					
					<div class="form_row">
						<strong>Upload</strong>
					</div>
					<div class="form_row">
						Select a file containing the changes to your campaign. Supported format - .xlsx<br />Please use this template <a href="/csv_template/Bulk_Add_Excel_Template.zip">here</a> (select channel / account first to view the correct template)
					</div>
					<div class="form_row upload-row">
						<input type="hidden" name="type" />
						<input type="file" name="file"/>
						<span id="upload_error" class="error_message"></span>
					</div>
					
					<hr>
					
					<div class="form_row">
						<div class="content_form_label">
							<label class="form_label">Post to Channel Options</label>
							<div class="clearfix"></div>
						</div>
						
						<div class="content_form_input">
							<input type="radio" name="status" value="0" checked> Upload changes in "Queued" status
							<br />
							<input type="radio" name="status" value="3"> Upload changes in "On Hold" status
							
						</div>
						<div class="clearfix"></div>
					</div>
					
					<input type="hidden" name="bulk_type" value="add">
					<input type="hidden" name="user_email" value="<%=@current_user_email.to_s%>"> 
					
					
					<div class="form_row">&nbsp;</div>
					<div class="form_row">
						<button type="button" class="button red_button submit_button" onclick="submitbulkUpload('apply');">Process</button>
						<button type="button" class="button white_button cancel_button" onclick="resetBulkUploadForm();">Cancel</button>
					</div>
					
				</form>
				
				<iframe id="hiddenUploadIframe" name="hiddenUploadIframe" height="0" width="0" frameborder="0" scrolling="yes"></iframe>
			</div>
			
			
		</div>
	</div>
</div>

app/views/networks/bulkuploadedit.html.erb
<div class="content_title">Bulk Upload</div>
<ul class="tab_menu">
	<li><a class="tab_tag history_log_tag" href="/bulkupload/add">Add</a></li>
	<li><a class="tab_tag history_log_tag active" href="javascript:;">Edit</a></li>
	<li><a class="tab_tag search_tag" href="/bulk/summary">Summary</a></li>
</ul>

<%
port_array = [81,83,89]
random_port = port_array.shuffle.sample
%>

<div class="content_outer">
	<div class="content_core">
		
		<div class="content_core_title">Use spreadsheets to make bulk changes to your campaigns</div>
		<hr>
		
		<div class="content_form">
			
			<div class="content_form">
				<form action="http://china.adeqo.com:<%=random_port.to_s%>/bulkjob" method="post" id="uploadForm" enctype="multipart/form-data" autocomplete="off" target="hiddenUploadIframe">
					
					<div class="form_row">
						<div class="content_form_label">
							<label class="form_label">Upload type:</label>
							<div class="clearfix"></div>
						</div>
						
						<div class="content_form_input">
							<input type="radio" name="upload_type" value="campaigns" checked> <label>Campaigns</label>
							<input type="radio" name="upload_type" value="adgroup"> <label>Ad Groups</label>
							<input type="radio" name="upload_type" value="ad"> <label>Ads</label>
							<input type="radio" name="upload_type" value="keyword"> <label>Keywords</label>
						</div>
						<div class="clearfix"></div>
					</div>
					<hr>
					<!--
					<div class="form_row">
						<div class="content_form_label" style="min-width:400px;">
							<label class="form_label">Please select channel and account:</label>
							<div class="clearfix"></div>
						</div>
						
						<div class="content_form_input">
							<select class="form_field" name="account" id="account">
								<%
								usernetwork_array = []
								@user_network = @db[:network_user].find('user' => session[:user_id].to_i)
								@db.close
								
								@user_network.each do |usernetwork|
									usernetwork_array << usernetwork["network_id"].to_i
								end
								
								# @networks = @db[:network].find('company_id' => @user_company_id.to_i)
								@networks = @db[:network].find('id' => { "$in" => usernetwork_array})
								if @networks.count.to_i > 0
									@networks.each do |network|
										%><option name="<%=network['type']%>" value="<%=network['id']%>"><%=network['name']%></option><%
									end
								end
								%>
							</select>
						</div>
						<div class="clearfix"></div>
						
					</div>
					<hr>
					-->
					
					<div class="form_row">
						<strong>Upload</strong>
					</div>
					<div class="form_row">
						Select a file containing the changes to your campaign. Supported format - .xlsx<br />
						<a href="/csv_template/Bulk_Edit_Excel_Template.zip">Example Here</a>
					</div>
					<div class="form_row upload-row">
						<input type="hidden" name="type" />
						<input type="file" name="file"/>
						<span id="upload_error" class="error_message"></span>
					</div>
					
					<hr>
					
					<div class="form_row">
						<div class="content_form_label">
							<label class="form_label">Post to Channel Options</label>
							<div class="clearfix"></div>
						</div>
						
						<div class="content_form_input">
							<input type="radio" name="status" value="0" checked> Upload changes in "Queued" status
							<br />
							<input type="radio" name="status" value="3"> Upload changes in "On Hold" status
							
						</div>
						<div class="clearfix"></div>
					</div>
					
					<input type="hidden" name="bulk_type" value="edit">
					<input type="hidden" name="user_email" value="<%=@current_user_email.to_s%>"> 
					
					
					<div class="form_row">&nbsp;</div>
					<div class="form_row">
						<button type="button" class="button red_button submit_button" onclick="submitbulkUpload('apply');">Process</button>
						<button type="button" class="button white_button cancel_button" onclick="resetBulkUploadForm();">Cancel</button>
					</div>
					
				</form>
				
				<iframe id="hiddenUploadIframe" name="hiddenUploadIframe" height="0" width="0" frameborder="0" scrolling="yes"></iframe>
			</div>
			
			
		</div>
	</div>
</div>

app/views/networks/campaignoverview.html.erb
<%= render partial: "campaign_tab_menu.html.erb" %>
 
      

<div class="content_outer content-no-padding">
	<div class="content_core">
		<div class="content_core tab_content">
			<form action="" method="post" id="campaignOverviewFilterForm" autocomplete="off">
				
				<input type="hidden" id="campaign_type" name="campaign_type" value="<%=@type.to_s%>"/>
				<input type="hidden" id="campaign_id" name="campaign_id" value="<%=@id.to_i%>"/>
				<input type="hidden" id="network_id" name="network_id" value="<%=@network_id%>"/>
				
				<ul class="nav nav-pills filters-nav">
					<!-- <li class="dropdown" id="custom-view-dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;" role="button">
							<img src="/images/icon/add-black.png" alt="Networks" title="Networks">
							Create Ad Group
						</a>
					</li>
	
					<li class="dropdown" id="custom-view-dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;" role="button">
							<img src="/images/icon/add-black.png" alt="Networks" title="Networks">
							Create Ad
						</a>
					</li> -->
	
					<li class="dropdown" id="custom-view-dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;" role="button" onclick="submitExportData();">
							<img src="/images/icon/export.png" alt="Export" title="Export">
							Export
						</a>
					</li>
	
					<li class="dropdown" id="custom-view-dropdown">
						<a href="/clickactivity/campaign/<%=@id%>">
							<img src="/images/icon/click-icon.png" alt="Networks" title="Networks">
							Click Activity
						</a>
					</li>
	
	
					<li class="pull-right">
						<a onclick="$('#date-range-dropdown .dropdown-toggle').dropdown('toggle');" href="javascript:;">
							<span class="caret"></span>
							<img src="/images/icon/calendar.png" alt="Networks" title="Networks">
						</a>
					</li>
					<li id="date-range-dropdown" class="dropdown pull-right">
						<a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;" role="button">
							<div class="text-right date-range">
								Last 7 days<br>
								10 June 2015 - 16 June 2015
							</div>
						</a>
						<ul class="dropdown-menu">
							<li class="text-center" onclick="setDate('Yesterday');applyFilter(this);"><a href="javascript:;">Yesterday</a></li>
							<li class="text-center" onclick="setDate('Last 7 days');applyFilter(this);"><a href="javascript:;">Last 7 days</a></li>
							<li class="text-center" onclick="setDate('Last 30 days');applyFilter(this);"><a href="javascript:;">Last 30 days</a></li>
							<li class="text-center" onclick="setDate('This Week');applyFilter(this);"><a href="javascript:;">This Week</a></li>
							<li class="text-center" onclick="setDate('Last Week');applyFilter(this);"><a href="javascript:;">Last Week</a></li>
							<li class="text-center" onclick="setDate('This Month');applyFilter(this);"><a href="javascript:;">This Month</a></li>
							<li class="text-center" onclick="setDate('Last Month');applyFilter(this);"><a href="javascript:;">Last Month</a></li>
							<li class="text-center" onclick="setDate('Last 3 Months');applyFilter(this);"><a href="javascript:;">Last 3 Months</a></li>
							<li class="text-center"><a class="no-highlight">Select Dates:</a></li>
							<li class="text-center">
								<a class="no-highlight">
									<div class="datepicker-container">
										<input type="text" id="start_date" name="start_date" class="datepicker-field">
										<span class="caret input-caret"></span>
									</div>
								</a>
								to
								<a class="no-highlight">
									<div class="datepicker-container">
										<input type="text" id="end_date" name="end_date" class="datepicker-field">
										<span class="caret input-caret"></span>
									</div>
								</a>
							</li>
							<li class="text-center">
								<a class="no-highlight" href="javascript:;">
									<button type="button" class="btn btn-red btn-xs btn-fullwidth" onclick="applyFilter(this, true);">Apply</button>
								</a>
							</li>
						</ul>
					</li>
				</ul>
			</form>
		</div>
	</div>
</div>

<div class="line-chart-container" id="line-chart-container1">
	<div class="line-chart-legend-container">
		<span class="line-chart-legend line-chart-legend-1"></span>
		<span class="line-chart-dropdown-container">
			<select id="line-chart-dropdown-1" class="chosen-select" onchange="genLineChart(this.value, '');">
				<option value="">None</option>
				<option value="impression" selected>Impr.</option>
				<option value="clicks">Clicks</option>
				<option value="pub_cost">Pub. Cost</option>
				<option value="avg_cpc">Avg. CPC</option>
				<option value="ctr">CTR</option>
				<option value="conversion">Conversions</option>
				<option value="conversion_rate">Conv. Rate</option>
				<option value="cpa">CPA</option>
				<option value="revenue">Revenue</option>
			</select>
		</span>

		<!-- <span class="line-chart-legend line-chart-legend-2"></span>
		<span class="line-chart-dropdown-container">
			<select id="line-chart-dropdown-2" class="chosen-select" onchange="genLineChart($('#line-chart-dropdown-1').val(), this.value);">
				<option value="">None</option>
				<option value="impression">Impr.</option>
				<option value="clicks" selected>Clicks</option>
				<option value="pub_cost">Pub. Cost</option>
				<option value="avg_cpc">Avg. CPC</option>
				<option value="ctr">CTR</option>
				<option value="conversion">Conversions</option>
				<option value="conversion_rate">Conv. Rate</option>
				<option value="cpa">CPA</option>
				<option value="revenue">Revenue</option>
			</select>
		</span> -->
	</div>

	<canvas id="line-chart"></canvas>
</div>

<div class="line-chart-container" id="line-chart-container2">
	<div class="line-chart-legend-container">
		<span class="line-chart-legend line-chart-legend-2"></span>
		<span class="line-chart-dropdown-container">
			<select id="line-chart-dropdown-2" class="chosen-select" onchange="genLineChart2('', this.value);">
				<option value="">None</option>
				<option value="impressions">Impr.</option>
				<option value="clicks" selected>Clicks</option>
				<option value="ctr">CTR</option>
				<option value="cost">Cost</option>
				<option value="avg_cpc">Avg. CPC</option>
				<option value="conversion">Conversions</option>
				<option value="conversion_rate">Conv. Rate</option>
				<option value="cpa">CPA</option>
				<option value="revenue">Revenue</option>
				<option value="profit">Profit</option>
				<option value="avg_pos">Avg. Pos.</option>
			</select>
		</span>
		
	</div>

	<canvas class="line-chart" id="line-chart2"></canvas>
</div>

<div id="campaign-overview-table-container">
	<table id="campaign-overview-table" class="table table-condensed">
		<thead>
			<tr>
				<th>Date</th>
				<th>Impr.</th>
				<th>Clicks</th>
				<th>Pub. Cost</th>
				<th>Avg. CPC</th>
				<th>CTR</th>
				<th>Conversions</th>
				<th>Conv. Rate</th>
				<th>CPA</th>
				<th>Revenue</th>
			</tr>
		</thead>
		<tbody class="text-right">
			
		</tbody>
		
		<tfoot>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
		</tfoot>
		
	</table>
</div>

app/views/networks/edit.html.erb
<h1>Editing network</h1>

<%= render 'form' %>

<%= link_to 'Show', @network %> |
<%= link_to 'Back', networks_path %>

app/views/networks/new.html.erb
<h1>New network</h1>

<%= render 'form' %>

<%= link_to 'Back', networks_path %>