config/routes.rb
Rails.application.routes.draw do

  resources :networks

  resources :users
  resources :homes

  root 'homes#index'
  
  
  get '/analytics' => 'networks#analytics'
  
  post '/deletetrackgoal' => 'networks#deletetrackgoal'
  post '/edittrackgoal' => 'networks#edittrackgoal'
  post '/addtrackgoal' => 'networks#addtrackgoal'

  get '/releasenotes' => 'networks#releasenotes'

  post '/campaignsettingupdate' => 'networks#campaignsettingupdate'

  post '/quickedit/keyword' => 'networks#quickeditkeyword'
  post '/quickadd/keyword' => 'networks#quickaddkeyword'

  get '/watchdog/history' => 'networks#watchdoghistory'

  post '/getwatchdogreport' => 'networks#getwatchdogreport'

  get '/pricing' => 'homes#pricing'
  get '/demo' => 'homes#demo'
  get '/contact_us' => 'homes#contact_us'
  get '/services' => 'homes#services'

  get '/services/search_engine_marketing' => 'homes#searchenginemarketing'
  get '/services/search_engine_optimization' => 'homes#searchengineoptimization'
  get '/services/social_media_marketing' => 'homes#socialmediamarketing'
  get '/services/content_localisation' => 'homes#contentlocalisation'

  post '/send_demo_email' => 'homes#send_demo_email'
  post '/send_contact_us_email' => 'homes#send_contact_us_email'

  get '/terms' => 'homes#terms'

  get '/demo_thank_you' => 'homes#demo_thank_you'
  get '/contact_us_thank_you' => 'homes#contact_us_thank_you'

  get '/cleanexportfile' => 'application#cleanexportfile'
  get '/cleanlogfile' => 'application#cleanlogfile'

  post '/getuser' => 'users#getuser'
  post '/edituser' => 'users#edituser'
  post '/switchuserstatus' => 'users#switchuserstatus'
  post '/createnewuser' => 'users#createnewuser'
  post '/removeuser' => 'users#removeuser'

  post '/campaign_api_sync' => 'networks#campaign_api_sync'
  post '/adgroup_api_sync' => 'networks#adgroup_api_sync'

  post '/createnetwork' => 'networks#createnetwork'
  post '/removenetwork' => 'networks#removenetwork'
  post '/getnetwork' => 'networks#getnetwork'
  post '/editnetwork' => 'networks#editnetwork'

  post '/csv' => 'networks#csv'
  get '/csv' => 'networks#csv'

  post '/login' => 'users#login'
  post '/logout' => 'users#logout'
  get '/logout' => 'users#logout'

  post '/updatepw' => 'users#updatepw'
  post '/updatemail' => 'users#updatemail'

  post '/addnetworkuser' => 'networks#addnetworkuser'
  post '/removenetworkuser' => 'networks#removenetworkuser'

  get '/dashboard' => 'homes#dashboard'
  get '/dashboard/detail' => 'homes#dashboarddetail'

  post '/getdashboard' => 'homes#getdashboard'

  post '/getdashboarddetail' => 'homes#getdashboarddetail'

  get '/account/' => 'users#account'
  get '/account/password' => 'users#editpassword'
  get '/account/user' => 'users#user'
  get '/account/tracking' => 'users#tracking'
  get '/account/portfolio' => 'users#portfolio'
  get '/account/goals' => 'users#goals' # leon goals

  get '/channel/accounts' => 'networks#channelaccounts'
  post '/getnetworkaccounts' => 'networks#getnetworkaccounts'
  post '/channel/sync' => 'networks#sync'

  get '/channel/:id/campaigns' => 'networks#campaigns'
  get '/campaigns' => 'networks#campaigns'
  get '/campaigns/:campaign_type' => 'networks#campaigns'
  get '/campaigns/:id/:type/:networkid/overview' => 'networks#campaignoverview'
  get '/campaigns/:id/:type/:networkid/setting' => 'networks#campaignsetting'
  get '/campaigns/:id/:type/:networkid/adgroup' => 'networks#campaignadgroup'

  get '/campaigns/:id/:type/:networkid/ads' => 'networks#campaignads'
  get '/campaigns/:id/:type/:networkid/adgroup/:adgroupid/ads' => 'networks#campaignads'

  get '/campaigns/:id/:type/:networkid/keyword' => 'networks#campaignkeyword'
  get '/campaigns/:id/:type/:networkid/adgroup/:adgroupid/keyword' => 'networks#campaignkeyword'

  get '/clickactivity/:type/:id' => 'networks#clickactivity'

  post '/getclickactivity' => 'networks#getclickactivity'

  post '/getcampaigns' => 'networks#getcampaigns'

  post '/getcampaignoverview' => 'networks#getcampaignoverview'

  post '/getcampaignadgroup' => 'networks#getcampaignadgroup'

  post '/getcampaignads' => 'networks#getcampaignads'

  post '/getcampaignkeyword' => 'networks#getcampaignkeyword'

  get '/getevent' => 'application#getevent'

  get '/get_event' => 'application#event'
  get '/event' => 'application#event'

  get '/getclick' => 'application#getclick'
  get '/click' => 'application#click'

  post '/sogous/updatead' => 'networks#sogouupdatead'
  post '/threesixties/updatead' => 'networks#threesixtyupdatead'
  post '/baidu/updatead' => 'networks#baiduupdatead'
  post '/shenmas/updatead' => 'networks#shenmaupdatead'

  post '/sogous/updatekeyword' => 'networks#sogouupdatekeyword'
  post '/threesixties/updatekeyword' => 'networks#threesixtyupdatekeyword'
  post '/baidu/updatekeyword' => 'networks#baiduupdatekeyword'
  post '/shenmas/updatekeyword' => 'networks#shenmaupdatekeyword'

  post '/sogous/updateadgroup' => 'networks#sogouupdateadgroup'
  post '/threesixties/updateadgroup' => 'networks#threesixtyupdateadgroup'
  post '/baidu/updateadgroup' => 'networks#baiduupdateadgroup'
  post '/shenmas/updateadgroup' => 'networks#shenmaupdateadgroup'

  post '/updatecampaign' => 'networks#allupdatecampaign'

  get '/advancedsearch' => 'networks#advancedsearch'
  get '/advancedsearchistory' => 'networks#advancedsearchistory'

  get '/getallleveldata' => 'networks#getallleveldata'
  post '/getallleveldata' => 'networks#getallleveldata'

  get '/getconversion' => 'application#getconversion'

  get '/bulkupload/add' => 'networks#bulkuploadadd'
  get '/bulkupload/edit' => 'networks#bulkuploadedit'
  get '/bulk/summary' => 'networks#bulksummary'

  post '/getbulkjob' => 'networks#getbulkjob'
  post '/cancelbulkjob' => 'networks#cancelbulkjob'
  post '/resumebulkjob' => 'networks#resumebulkjob'

  post '/bulkaddcampaign' => 'networks#bulkaddcampaign'
  post '/bulkaddadgroup' => 'networks#bulkaddadgroup'
  post '/bulkaddad' => 'networks#bulkaddad'
  post '/bulkaddkeyword' => 'networks#bulkaddkeyword'

  post '/bulkeditcampaign' => 'networks#bulkeditcampaign'

  post '/advancesearchjob' => 'networks#advancesearchjob'
  post '/advancesearchjobupdate' => 'networks#advancesearchjobupdate'
  post '/canceladvancesearchjob' => 'networks#canceladvancesearchjob'

  post '/advancesearchadgroup' => 'networks#advancesearchadgroup'
  post '/advancesearchadgroupupdate' => 'networks#advancesearchadgroupupdate'

  post '/getadvancesearch' => 'networks#getadvancesearch'

  post '/getcampaignbynetworkid/:id' => 'networks#getcampaignbynetworkid'

  post '/getadgroupbycampaignid/:type/:id' => 'networks#getadgroupbycampaignid'

  get '/test' => 'application#test'

  get '*unmatched_route' => 'application#not_found'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy]
  # before_action :authuser, only: [:index,:show,:updatepw,:updatemail,:companyuser]
  
  before_action :authuser, except: [:createnewuser,:logout,:login]
  layout "home" 
  
  require "azure"
  
  require 'rubygems'
  require 'mongo'
  
  
  def goals
      @goals = @db[:conversion_rules].find('company_id' => @user_company_id)
      @db.close()
  end
  
  def portfolio
    
  end
  
  def tracking
    
  end
  
  def account
    @current_user_network = @db[:network].find('company_id' => @user_company_id)
    @db.close()
  end
  
  
  def edituser
    
      if @user_role == "read"
        data = {:message => "You cant delete anything", :status => "false"}
        return render :json => data, :status => :ok
      end
    
      user_id = params[:id]
      user = @db[:user].find('id' => user_id.to_i)
      @db.close()
      
      if user.count.to_i != 1
          data = {:message => "Wrong input", :status => "false"}
          return render :json => data, :status => :ok
      else
        
          @update_name =  params[:signup_name]
          @update_email =  params[:signup_email]
          @update_password =  params[:signup_password]
          @update_user_role =  params[:user_role]
          
          if @user_role == "read"
              data = {:message => "You can't edit anything", :status => "false"}
              return render :json => data, :status => :ok 
          end
          
          
          if @update_password.to_s != ""
              @encrypted_password = BCrypt::Password.create(@update_password.to_s)
              @db[:user].find('id' => user_id.to_i).update_one('$set'=> { 'password' => @encrypted_password })
              @db.close()
          end
          
          @db[:user].find('id' => user_id.to_i).update_one('$set'=> { 'email' => @update_email, 'username' => @update_name, 'role' => @update_user_role })
          @db.close()
          
          data = {:message => "Done", :status => "true", :user => user}
          return render :json => data, :status => :ok 
          
      end
  end
  
  
  def switchuserstatus
    
      if @user_role == "read"
        data = {:message => "You cant edit anything", :status => "false"}
        return render :json => data, :status => :ok
      end
    
      user_id = params[:id]
      user_status = params[:status]
      
      user = @db[:user].find('id' => user_id.to_i)
      @db.close()
      
      if user.count.to_i != 1
          data = {:message => "Wrong input", :status => "false"}
          return render :json => data, :status => :ok
      else
          @db[:user].find('id' => user_id.to_i).update_one('$set'=> { 'status' => user_status.to_s })
          @db.close()
          
          data = {:message => "Done", :status => "true"}
          return render :json => data, :status => :ok 
      end
  end
  
  
  def getuser
    
      if @user_role == "read"
        data = {:message => "You cant edit anything", :status => "false"}
        return render :json => data, :status => :ok
      end
      
      user_id = params[:id]
      sub_users = @db[:user].find('id' => user_id.to_i)
      @db.close()
      
      if sub_users.count.to_i != 1
          data = {:message => "Wrong input", :status => "false"}
          return render :json => data, :status => :ok
      else          
          data = {:message => "Done", :status => "true", :user => sub_users}
          return render :json => data, :status => :ok 
      end
  end
  
  
  def user
    
    @current_user.each do |user|
      @current_user_password = user["password"]
      @userid = user["id"]
      @company_id = user["company_id"] 
    end
    
    @sub_users = @db[:user].find('company_id' => @company_id)
    @db.close()
    
  end
  
  
  def updatepw
    
    @input_current_pw =  params[:up_c_password]
    @input_new_pw =  params[:up_n_password]
    
    @current_user.each do |user|
      @current_user_password = user["password"]
      @id = user["id"]
    end
    
    @encrypted_password = BCrypt::Password.new(@current_user_password)
    @auth = (@encrypted_password == @input_current_pw)
    
    if @auth == false
      data = {:message => "Current PW not correct", :status => "false"}
      return render :json => data, :status => :ok
    end
    
    @encrypted_password = BCrypt::Password.create(@input_new_pw.to_s)
    
    @db[:user].find('id' => session[:user_id]).update_one('$set'=> { 'password' => @encrypted_password })
    @db.close()
    @db[:user].find('id' => session[:user_id]).update_one('$set'=> { 'last_login' => @now })
    @db.close()
    
    data = {:message => "PW Updated", :status => "true"}
    return render :json => data, :status => :ok
  end
  
  
  
  
  
  def updatemail
    #put logout here to avoid hack, this function is not in use for now
    
    session[:user_id] = nil
    return redirect_to "/"
    # @input_current_pw =  params[:um_c_password]
    # @input_new_email =  params[:um_n_mail]
#    
    # @current_user.each do |user|
      # @current_user_password = user["password"]
      # @id = user["id"]
    # end
#    
    # @encrypted_password = BCrypt::Password.new(@current_user_password)
    # @auth = (@encrypted_password == @input_current_pw)
#     
    # if @auth == false
      # data = {:message => "Current PW not correct"}
      # return render :json => data, :status => :ok
    # end
#     
    # @db[:user].find('id' => session[:user_id]).update_one('$set'=> { 'password' => @input_new_email })
  end
  
  
  
  def createcompany
  end
  
  
  
  
  
  def removeuser
    
    
    if @user_role != "super"
      # session[:user_id] = nil
      # return redirect_to "/"
      data = {:message => "You cant remove anything", :status => "false"}
      return render :json => data, :status => :ok
    end
    
    @id =  params[:remove_userid]
    @db[:user].find('id' => @id.to_i).delete_one
    @db.close()
    # @result = @db[:user].find('id' => @id)
    
    @db[:network_user].find('user' => @id.to_i).delete_many
    @db.close()
    
    data = {:message => "Removed", :status => "true", :id => @id}
    return render :json => data, :status => :ok
  end
  
  def createnewuser
    # Mongoid.database.connection.close() 
    last_user_id = get_last_id("user")
    last_company_id = get_last_id("company")
    
    @username =  params[:signup_name]
    
    @email =  params[:signup_email]
    @password = params[:signup_password]
    
    @encrypted_password = BCrypt::Password.create(@password.to_s)

    @user_role = params[:user_role]
    @company_role = params[:company_role]
    
    @company = params[:signup_company]
    @user_company_id = params[:signup_company_id]
    
    @sub_user = params[:sub_user]
    
    
    current_user = @db[:user].find('email' => @email.to_s)
    @db.close()
    current_company = @db[:company].find('name' => @company.to_s)
    @db.close()
    
    if current_company.count == 1
      data = {:message => "This Company exist, can't use this name", :status => "false"}
      return render :json => data, :status => :ok
    end
     
    if current_user.count == 1
      data = {:message => "This user exist, use another email", :status => "false"}
      return render :json => data, :status => :ok      
    else
      
      @user_id = last_user_id.to_i + 1
      @company_id = last_company_id.to_i + 1
      
      if @user_company_id.nil?
          @user_company_id = @company_id
      end
      
      if @username.nil?
          @username = @email
      end
      
      if !@user_role.nil?
        @db[:user].insert_one({ id: @user_id.to_i, company_id: @user_company_id.to_i, email: @email, username: @username, password: @encrypted_password, role: @user_role.to_s, status: 'start', create_date: @now, last_login: @now })
        @db.close()
        update_last_id("user",@user_id)
      end
      
      if !@company_role.nil?
        @db[:company].insert_one({ id: @company_id.to_i, name: @company.to_s, user_id: @user_id, role: @company_role.to_s, status: 'start', create_date: @now })
        @db.close()
        update_last_id("company",@company_id)
      end
      
      if @sub_user.to_i == 0
          session[:user_id] = @user_id
          session[:user_role] = @user_role.to_s
      end 
           
      data = {:message => "Add User Done", :user_id => @user_id, :company_id => @company_id, :status => "true"}
      return render :json => data, :status => :ok
      
    end
  end
  
  def logout
    session[:user_id] = nil
    session[:user_network_id_array] = nil
    
    session[:start_date] = nil
    session[:end_date] = nil
    
    session[:watchdog_end_date] = nil
    session[:watchdog_start_date] = nil
    
    session[:bulk_end_date] = nil
    session[:bulk_start_date] = nil
    
    session[:adv_end_date] = nil
    session[:adv_start_date] = nil
    
    return redirect_to "/"
  end
  
  
  def login
    session[:user_network_id_array] = nil
    @email =  params[:login_email]
    @password = params[:login_password]
    
    if params[:login_email].nil?
      data = {:message => "Input email empty", :status => "false"}
      return render :json => data, :status => :ok
    end
    
    if params[:login_password].nil?
      data = {:message => "Input password empty", :status => "false"}
      return render :json => data, :status => :ok  
    end
    
    
    @current_user = @db[:user].find('email' => @email)
    @db.close()
    @current_user_count = @current_user.count.to_i
    
    if @current_user_count == 0
      data = {:message => "This user was not found in the system.", :status => "false"}
      return render :json => data, :status => :ok
    end
    
    if @current_user_count > 1
      data = {:message => "Something Wrong with your Account, please call us.", :status => "false"}
      return render :json => data, :status => :ok
    end
    
    @current_user.each do |user|
      @current_user_password = user["password"]

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_account_tab_menu.html.erb
<ul class="tab_menu">
	<li><a class="tab_tag ad_account_tag" href="/account">Ad Accounts</a></li>
	<li><a class="tab_tag user_tag" href="/account/user">Users</a></li>
	<li><a class="tab_tag portfolio_tag" href="/account/portfolio">Portfolio</a></li>
	<li><a class="tab_tag tracking_tag" href="/account/tracking">Tracking</a></li>
	<!-- <li><a class="tab_tag goals_tag" href="/account/goals">Goals</a></li> -->
	<li><a class="tab_tag password_tag" href="/account/password">Password</a></li>

</ul>


<script>
	if(/\/account\/user/i.test(window.location.href)){
		$(".user_tag").addClass("active");
	}
	else if(/\/account\/portfolio/i.test(window.location.href)){
		$(".portfolio_tag").addClass("active");
	}
	else if(/\/account\/tracking/i.test(window.location.href)){
		$(".tracking_tag").addClass("active");
	}
	else if(/\/account\/password/i.test(window.location.href)){
		$(".password_tag").addClass("active");
	}
	// leon goals
	else if(/\/account\/goals/i.test(window.location.href)){
		$(".goals_tag").addClass("active");
	}else if (/account/i.test(window.location.href)){
		$(".ad_account_tag").addClass("active");
	}
</script>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

app/views/users/editpassword.html.erb
<div class="content_title">Account Settings</div>
<%= render partial: "account_tab_menu.html.erb" %>

<div class="content_outer">
	<div class="content_core">
		<div class="content_core_big_title">Change Adeqo Account Password</div>
		<hr/>
		<div class="content_form">
			<form action="" method="post" id="resetPasswordForm" autocomplete="off">
				<div class="form_row">
					<div class="content_form_label pull-left">
						<label for="reset_current_password" class="form_label pull-right">Current Password:</label>
						<div class="clearfix"></div>
					</div>
					<div class="content_form_input pull-left">
						<input id="reset_current_password" name="up_c_password" type="password" autocomplete="off" class="form_field"/><br/>
				 		<span id="reset_current_password_error" class="error_message"></span>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="form_row">
					<div class="content_form_label pull-left">
						<label for="reset_new_password" class="form_label pull-right">New Password:</label>
						<div class="clearfix"></div>
					</div>
					<div class="content_form_input pull-left">
						<input id="reset_new_password" name="up_n_password" type="password" autocomplete="off" class="form_field"/><br/>
				 		<span id="reset_new_password_error" class="error_message"></span>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="form_row">
					<div class="content_form_label pull-left">
						<label for="reset_confirm_new_password" class="form_label pull-right">Confirm New Password:</label>
						<div class="clearfix"></div>
					</div>
					<div class="content_form_input pull-left">
						<input id="reset_confirm_new_password" name="up_cn_password" type="password" autocomplete="off" class="form_field"/><br/>
				 		<span id="reset_confirm_new_password_error" class="error_message"></span><br/>
				 		
				 		<div class="button red_button submit_button pull-right" onclick="submitResetPassword();">Save</div>
					</div>
					<div class="clearfix"></div>
				</div>
			</form>
		</div>
	</div>
</div>
<div class="content_bottom">Have question about your account? Email us at <a href="mailto:sales@bmgww.com" target="_top"><u>sales@bmgww.com</u></a> for assistance.</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/portfolio.html.erb
<div class="content_title">Account Settings</div>
<%= render partial: "account_tab_menu.html.erb" %>

<div class="content_outer">
	<div class="content_core">
		<%
		
		@sub_users = @db[:user].find('company_id' => @user_company_id)
		@db.close()
		
		@network = @db[:network].find('company_id' => @user_company_id)
		@db.close()
		
		@network_arr = []
		@sub_users_arr = []
		
		@all_network_id_str = ""
		
		@network_hash = {}
		@network_id_arr = []
		@sub_users_id_arr = []
		
		
		if @sub_users.count.to_i > 0
			@sub_users.each do |sub_users|
				@sub_users_arr << sub_users
				@sub_users_id_arr << sub_users["id"]
			end
		end
		
		if @network.count.to_i > 0
			@network.each do |network|
				@network_arr << network
				
				@network_id_arr << network["id"].to_s
				@network_hash["id"+network["id"].to_s] = network
				
			end
		end
		
		@all_network_id_str = @network_id_arr.join(",")
		
		@user_allow_network_hash = {}
		@user_allow_network = @db[:network_user].find("user" => { "$in" => @sub_users_id_arr})
		
		@user_allow_network.each do |user_allow_network|
			if @user_allow_network_hash["id"+user_allow_network["user"].to_s]
				@user_allow_network_hash["id"+user_allow_network["user"].to_s] += "," +user_allow_network["network_id"].to_s
			else
				@user_allow_network_hash["id"+user_allow_network["user"].to_s] = user_allow_network["network_id"].to_s
			end
		end
		
		
		
		
		if @sub_users_arr.count.to_i > 0
			@sub_users_arr.each do |subuser|		
				if session[:user_id] != subuser["id"].to_i
					
					user_network_id_array = []
					not_user_network_id_array = []
					
					if !@user_allow_network_hash["id"+subuser["id"].to_s].nil?
						
						user_network_id_array = @user_allow_network_hash["id"+subuser["id"].to_s].split(",")
						user_network_id_array = user_network_id_array.uniq.sort 
						
						not_user_network_id_array = @network_id_arr - user_network_id_array
						
						# concat @network_id_arr
						# concat "<br />".html_safe
						# concat user_network_id_array
						# concat "<br />".html_safe
						# concat	@network_id_arr - user_networl_id_array
					else
						# user_network_id_array = @all_network_id_str.split(",")
						# user_network_id_array = user_network_id_array.uniq.sort
# 						
						# not_user_network_id_array = []
						
						
						not_user_network_id_array = @all_network_id_str.split(",")
						# not_user_network_id_array = user_network_id_array.uniq.sort
						
						user_network_id_array = []
					end
					
					# concat "<br /><br />".html_safe
					%>
					
					<div class="portfolio_container">
						<div class="content_item"><%=subuser["username"]%> (<%=subuser["email"]%>)</div>
						
						<div class="content_item">
							<div class="portfolio_select_container">
								<div class="portfolio_select_header button" onclick="toggleHiddenPortfolio(this);">Advertising accounts in this portfolio:<span class="downArrow pull-right"></span></div>
								<div class="portfolio_select_hidden">
									<hr/>
									<form action="" method="post" id="portfolioDeleteForm_<%=subuser["id"]%>" autocomplete="off">
										<input type="hidden" name="user_id" id="delete_user_id" value="<%=subuser["id"]%>">
											<% 
											if user_network_id_array.count.to_i > 0 
												user_network_id_array.each do |user_network_id_array_d|
													if !@network_hash["id"+user_network_id_array_d.to_s].nil?
											%>
													<div class="portfolio_select_option"><input type="checkbox" name="network_id_array[]" value="<%=@network_hash["id"+user_network_id_array_d.to_s]["id"]%>"/><%=@network_hash["id"+user_network_id_array_d.to_s]["name"]%></div>
											<%      end
												end
											end 
											%>
									</form>
									<hr/>
									<div class="portfolio_select_button_container">
										<input type="checkbox" value="<%=subuser["id"]%>" onchange="selectAllPortfolioOption(this,'portfolioDeleteForm_<%=subuser["id"]%>');"/>Select all
										<div class="button red_button submit_button central_button" onclick="submitPortfolioDelete('portfolioDeleteForm_<%=subuser["id"]%>');">Remove from this portfolio</div>
									</div>
								</div>
							</div>
						</div>
						
						<div class="content_item">
							<div class="portfolio_select_container">
								<div class="portfolio_select_header button" onclick="toggleHiddenPortfolio(this);">Select Advertising account to add to this portfolio <span class="downArrow pull-right"></span></div>
								<div class="portfolio_select_hidden">
									<hr/>
									<form action="" method="post" id="portfolioAddForm_<%=subuser["id"]%>" autocomplete="off">
										<input type="hidden" name="user_id" id="add_user_id" value="<%=subuser["id"]%>">
										<%
										
										if not_user_network_id_array.count.to_i > 0 
											not_user_network_id_array.each do |not_user_network_id_array_d|
										%>
												<div class="portfolio_select_option"><input type="checkbox" name="network_id_array[]" value="<%=@network_hash["id"+not_user_network_id_array_d.to_s]["id"]%>"/><%=@network_hash["id"+not_user_network_id_array_d.to_s]["name"]%></div>
										<% 
											end
										end 
										%>
									</form>
									<hr/>
									<div class="portfolio_select_button_container">
										<input type="checkbox" value="<%=subuser["id"]%>" onchange="selectAllPortfolioOption(this,'portfolioAddForm_<%=subuser["id"]%>');"/>Select all
										<div class="button red_button submit_button central_button" onclick="submitPortfolioAdd('portfolioAddForm_<%=subuser["id"]%>');">Add to this portfolio</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<%
				end
			end
		end
		
		%>
		
		
		<!-- <div class="portfolio_container">
			<div class="content_item">John Smith (john@smith.com)</div>
			<div class="content_item"><span class="remove_icon button" title="remove" onclick=""></span>Qihoo 360: BMG - Asia</div>
			<div class="content_item"><span class="remove_icon button" title="remove" onclick=""></span>BMG - North America</div>
			<div class="content_item">
				<div class="portfolio_select_container">
					<div class="portfolio_select_header button" onclick="toggleHiddenPortfolio(this);">Select Advertising account to add to this portfolio <span class="downArrow pull-right"></span></div>
					<div class="portfolio_select_hidden">
						<hr/>
						<form action="" method="post" id="portfolioForm_1" autocomplete="off">
							<div class="portfolio_select_option"><input type="checkbox" name="account_array[]" value="apihotel@sogou.com"/>apihotel@sogou.com</div>
							<div class="portfolio_select_option"><input type="checkbox" name="account_array[]" value="apihotel@sogou.com"/>apihotel@sogou.com</div>
							<div class="portfolio_select_option"><input type="checkbox" name="account_array[]" value="apihotel@sogou.com"/>apihotel@sogou.com</div>
						</form>
						<hr/>
						<div class="portfolio_select_button_container">
							<input type="checkbox" value="1" onchange="selectAllPortfolioOption(this,'portfolioForm_1');"/>Select all
							<div class="button red_button submit_button central_button" onclick="">Submit</div>
						</div>
					</div>
				</div>
			</div>
		</div> -->
		

	</div>
</div>
<div class="modal fade" id="portfolio_error_modal" tabindex="-1" role="dialog" aria-labelledby="portfolio_error_modal_label">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<div class="modal_container">
					<div id="portfolio_error_content" class="modal_title user_remove_title"></div>
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="button red_button submit_button" onclick="$('#portfolio_error_modal').modal('hide');">OK</div>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>